[CP-1111] feat: upgrade to php 8.1
LinioIT/monolog-cascade pull request #5
Opened 2022-12-14 13:20 UTC by Felynx3

This PR updates PHP version to 8.1 with some extras descripted bellow.

### Changes 
- upgrade php version in composer.json
- upgrade all dependencies
- add tags/branches/php-version relations information table in Readme
- add ci workflow
- add static analysis

2022-12-14 13:32 UTC, GuillermoFarias requested changes

2022-12-14 13:32 UTC, GuillermoFarias commented on composer.json
> +            "@test:mutation",
this project use mutations test 👀 ?

2022-12-14 13:34 UTC, Felynx3 commented on composer.json
> +            "@test:mutation",
Oooh nice catch, thank you, I'll fix it

2022-12-14 13:49 UTC, Felynx3 commented on composer.json
> +            "@test:mutation",
Fixed

2022-12-14 13:52 UTC, ibrito182 approved these changes, later dismissed

2022-12-14 18:14 UTC, GuillermoFarias requested changes

2022-12-14 18:14 UTC, GuillermoFarias commented on .github/workflows/continuous-integration.yml 
> +    name: Unit tests, coverage and mutation
:trollface: se le quedó una mención a  `mutation`

2022-12-14 20:58 UTC, Felynx3 commented on .github/workflows/continuous-integration.yml 
> +    name: Unit tests, coverage and mutation
hahhaa fixed

2022-12-14 21:33 UTC, GuillermoFarias approved these changes

2022-12-15 20:17 UTC, tamara-dietz approved these changes

2022-12-15 20:21 UTC, MarioDevment approved these changes

2022-12-16 13:55 UTC, merged